### ISSUE TITLE
Temporal Extension - Change in Color

### ISSUE THREAD

**Issue by pftq** [ali-vilab/VACE#44]
The temporal extension is neat on paper, but I'm getting a shift in color that makes it obvious where the extension occurs.  Is this a limitation or is there some way to better tune the output? I'm using the WAN version.

**Comment by hanzhn** [comment]
I guess you didn't pass mask to the model, so VACE recognized the video are fully changeable. 
You need to pass a mask video, in which all white are the frames you need to do changes, all black are which to keep untouched.

**Comment by pftq** [comment]
I've written tutorials and posted many examples on using the masking feature in VACE - https://www.reddit.com/r/StableDiffusion/comments/1k83h9e/seamlessly_extending_and_joining_existing_videos/

I am passing a mask along yes.  The color shift I'm talking about is a very subtle orange-reddish tint that happens the more you pass the same video through VACE (for example, re-extending extended footage).  Over time without manual correction, your video gets redder and redder.  Try it with a video with brownish incandescent lighting and the brown will eventually become red.

**Comment by YewMeng** [comment]
> I've written tutorials and posted many examples on using the masking feature in VACE - https://www.reddit.com/r/StableDiffusion/comments/1k83h9e/seamlessly_extending_and_joining_existing_videos/
> 
> I am passing a mask along yes. The color shift I'm talking about is a very subtle orange-reddish tint that happens the more you pass the same video through VACE (for example, re-extending extended footage). Over time without manual correction, your video gets redder and redder. Try it with a video with brownish incandescent lighting and the brown will eventually become red. Skin tones are especially affected.

Hi @pftq 
I did some testing in ComfyUI and found that the color shift issue is actually caused by video compression.

In my v1.0.0 workflow (https://civitai.com/models/1615710?modelVersionId=1828560), I was using the output from the Video Combine node (MP4 format) as input for VACE. As seen in the gallery, each extension introduced a noticeable color shift (the pool is getting greener and greener with each video extension) very similar to what you described.

To confirm, I then ran a basic test using just a Video Upload node and a Video Combine node (without any VACE nodes), and the same color shift occurred. That pointed to the compression itself as the root cause.

In my updated v1.1.1 workflow (https://civitai.com/models/1615710?modelVersionId=1859503), I switched to using a lossless WebP format instead of MP4, and the color shifting issue was resolved.

**Comment by pftq** [comment]
I looked into this possibility as well but it only reduces the issue, not eliminates.  I had already moved to exporting PNG sequences instead of MP4, but that gradual tint is still slightly there.  It doesn't happen with other models in ComfyUI (ie Hunyuan).

**Comment by lym000000** [comment]
Noted, I was specifically referring to the color shift introduced by video compression. 

That said, I’ve also noticed slight tint/exposure/color changes in my generations. Seems like others are running into the same issue as well (e.g., [this Reddit comment](https://www.reddit.com/r/StableDiffusion/comments/1ktljys/comment/muc8e0r/)). Hopefully this gets improved in future updates.

**Comment by pftq** [comment]
In case it helps anyone else, this is the color correction in After Effects that I'm using which gets pretty close to canceling out the effect.

![Image](https://github.com/user-attachments/assets/6addacd5-2dc6-4f98-94f2-ad1d2ff34358)

**Comment by lym000000** [comment]
Also came across this relevant proposal on applying color correction after VAE decoding: https://github.com/MeiGen-AI/MultiTalk/issues/22

**Comment by pftq** [comment]
The PR you linked to is just a shortcut to extend videos without use of a video editor to prepare new video inputs.  His comment about color and masking is just his opinion on the issue and not addressed by the PR itself.

The color drift happens even without ComfyUI when VACE is used just from the github repo and even on your own examples.  It happens on all videos, not just temporal extension, and also tints the color of existing footage. You can even see it in your example benchmark output videos.

SRC: benchmarks/VACE-Benchmark/assets/examples/inpainting/src_video.mp4
Mask: benchmarks/VACE-Benchmark/assets/examples/inpainting/src_mask.mp4
Output: 

Comparison:
SRC

![Image](https://github.com/user-attachments/assets/2d0f3021-f737-4192-aa1e-ea28f4ef241f)
Output

![Image](https://github.com/user-attachments/assets/25d30fdc-2be2-4a4b-ac3d-dc7d3d33a2d1)

The white building that is lit up orange ends up being closer to pink and the blue hue in the sky ends up closer to purple.  Over many passes, this will compound until you end up with very reddish footage unless you correct it in postproduction.

**Comment by deepbeepmeep** [comment]
I concur. I have checked numerous times the mask for the overlapped frames is black (that is 0 before getting into the VAE encoder). Everything else in Vace work greats and the more I use Vace the more 

I am impressed by how versatile and powerful Vace is. I cant believe you have managed to fit as many control nets tasks in a single model. But sadly there is a color and detail shift no matter what with new generated frames. 

I am no expert but I believe that given a big part of the generated content come from the input that is persisent at all time in the input of the control net there should be way to mitigate this issue.

**Comment by pftq** [comment]
If it helps, the color seems to shift less when the resolution is higher.  1920x1088 has the shift very slight while the tint is much more extreme (reddish) with low resolution <=480p

**Comment by deepbeepmeep** [comment]
1) I don’t think the VAE is the culprit as I have tried also to recycle directly the latent samples that came from the previous generation and this didn’t solve the tint issue 

2) I will try to apply a full black mask on a source video and use the output video as a new source video

**Comment by able2608** [comment]
VAE seems to not be causing that much of an issue. I have compared the difference between original vs VAE processed and original vs VACE processed (albeit using ComfyUI and a quantized version). The output of VAE does not cause much color shift, only very small details seems to change (mostly at the edge of the object, requires direct subtraction to visualize), but after VACE process it changes a lot, not just minor structure but also noticeable color shift that degrades the extended clips within 4~5 passes.
For me the color shift does not always manifest as a constant shift towards a color, sometimes looks more like artifacts (patches of smooth and subtle change in colors), but it mostly ends up with videos that contains oversaturated colors with noticeable color changes even on parts that have solid color at the start. I have tried using color matching to correct the issue, but it seems that color matching sometimes over-corrects and is not consistent.
From my observation (that noticeable color shift is present at the output even with proper full-frame masking when doing temporal extension), it seems that VACE's latent space does not allow it to always accurately reconstruct whatever is at its input, causing the output to drift quite a bit. If this is not isolated or possibly due to quantization, then it might require a FramePack version of WAN to fix (obviously, to fit all the frames into the same sequence and directly do long video generation).

**Comment by pftq** [comment]
Regarding details that shift in the original footage, I do not get that issue but I use a very low CFG (<=2).  Sometimes I go down to 1 if I am trying to really maintain the same hair and other minor details in the extension.  So just a tip for @deepbeepmeep on that issue.  As a workaround for reduced guidance/control, sometimes I do a first pass with high CFG to get a few frames as an end frame and then do another pass to restore the details while guiding to the endframe of the first pass (and then additional passes to selectively restore details on lower CFG).  A bit annoying but just to suggest some workarounds in the mean time that I'm using.

But the CFG does not help with the color drift issue, which seems be caused by something else (but which as I mentioned earlier seems to be reduced but not fully eliminated when resolution is higher above 1080p).

**Comment by hoveychen** [comment]
I came across the same color issue. It's really easy to reproduce. 

Provide any image to VACE, and all black mask. 
The expected result is that all the frames are identical to the given image, due to all black mask.
The actual result is that the first frame's color changed noticeably.

![Image](https://github.com/user-attachments/assets/24aa8752-1ad2-43de-a05d-8b89de42adb4)

Using a pure color image

![Image](https://github.com/user-attachments/assets/674e14f8-ff67-4737-933f-44dddcee5c31)

BTW: This is the testing workflow

[VACE BUG.json](https://github.com/user-attachments/files/20924947/VACE.BUG.json)

**Comment by able2608** [comment]
> I came across the same color issue. It's really easy to reproduce.
> 
> Provide any image to VACE, and all black mask. The expected result is that all the frames are identical to the given image, due to all black mask. The actual result is that the first frame's color changed noticeably.
> 
> ![Image](https://github.com/user-attachments/assets/24aa8752-1ad2-43de-a05d-8b89de42adb4)
> 
> Using a pure color image
> 
> ![Image](https://github.com/user-attachments/assets/674e14f8-ff67-4737-933f-44dddcee5c31)
> 
> BTW: This is the testing workflow
> 
> [VACE BUG.json](https://github.com/user-attachments/files/20924947/VACE.BUG.json)

Can confirm this issue. This is what I got during testing.

**Comment by pftq** [comment]
Thanks all for confirming this issue.  It's good to confirm I wasn't the only one seeing this.

> btw. It's also confirmed that higher resolution results in more similar color.
> 
> ![Image](https://github.com/user-attachments/assets/df3018bb-1818-4103-8bdb-b913d2dbee24)
> 
> ![Image](https://github.com/user-attachments/assets/50a8cad9-2a5f-4487-bfb1-8e0c7a5480d5)
> 
> ![Image](https://github.com/user-attachments/assets/2c1e1931-266a-4fee-8d4a-184ecb5aff2a)

That's very interesting and excellent to see the hunch was correct.  Thanks for doing the test.

**Comment by rishipandey125** [comment]
@pftq so the color shift doesn't happen because of the double encode / decode of the VAE? that is always what I assumed when using the extension system

**Comment by MikeMcLuckie** [comment]
Just adding my voice to the choir. Hoping the issue gets some attention as this severely reduces VACE's usefulness. The color changes seem to be different from video to video, making this very difficult (or impossible) to work around.

**Comment by pftq** [comment]
No it happens in general.  I've used VACE on hundreds of video clips now, different seeds, different resolutions, different steps, different cfg, shift, with and without loras, - the issue is persistent.

**Comment by jiangzeyinzi** [comment]
@pftq I am only providing a possible clue for alleviation, which is to use different seeds for each round when generating segments of long videos; this may help. 
Currently, the reasons seem quite complex. On one hand, the accumulated errors from generating frames based on the generated video could stem from either the DIT or the VAE. On the other hand, VACE’s capability of converting gray to color task might also mislead the actual colors, so this task might need to be removed. 

Additionally, the aforementioned pure color image experiment is intended to test the VAE module only, without including the VACE module.

**Comment by deepbeepmeep** [comment]
_To avoid any confusion in these discussions I think we must distinguish different kinds of color shifting:_

Let's assume we want to _outpaint the bottom half of a video and keep the upper part unchanged_ (masks are set approprietaly with 0 on the upper part and 1 on the bottom part).

If  all the frames of a video are outpainted like this, the color shift will be light on both the upper part and the outpainted part and globally the frames will look nice and consistent

On the other hand if  single frame (for instance the first) is a full frame (with no outpainting at all) the color shift will appear progressively on the outpainted parts of all the following frames. There will be still a lighter colorshift on the upper part (which is supposed to be copied as is) but it will be much lighter. With enough frames the outpainted parts will be quite visible and its quality will be much worse than in the previous case.


**In summary :** 
a) a _light color_ shift appears no matter what between the control video and the output video, even if the output video is supposed to be identical to the control video
b) a _stronger color_ shift appears whenever new frames (or part of these) are extrapolated based on past frames

I don't think that the a) case is a real problem, because the light colorshift will be consistent through all the generated videos and can be fixed easily with a color correction post processing.

However when one tries to extend a generated video (required for window sliding) one fits into the b) case. Each new extension degrade significantly the output video quality. This is really the area which needs to be solved be able to generate long videos

**Comment by deepbeepmeep** [comment]
So both issues must be solved.

The reason why I stressed case b) is because the color degradation is much worse and it is caused by a single causal temporal frame in the loop which can not be avoided if you want to generate long videos. 

Besides in my own testing  just changing the cfg didn’t solve b) and when using accelerators loras guidance must be 1 anyway.

**Comment by hoveychen** [comment]
> [@pftq](https://github.com/pftq) Would trying different seeds in each editing operation help alleviate the issue?
> 
> [@hoveychen](https://github.com/hoveychen) This case is quite intuitive. Could you compare whether there is a shift issue when encoding and decoding a pure color image with the VAE?

VAE was the first thing to inspect, but turned out that it has minor affect on the overall color shifting issue. 

<img width="1536" height="560" alt="Image" src="https://github.com/user-attachments/assets/4364fec7-7532-41de-92b0-655aef89630e" />

**Comment by hoveychen** [comment]
> [@hoveychen](https://github.com/hoveychen) Thank you for your experiment. If it's convenient for you, could you use VAE to recode the image and then run VAE multiple times to be more aligned with practical use?

<img width="2560" height="560" alt="Image" src="https://github.com/user-attachments/assets/13c4f62e-3dd9-41f8-a1e2-e7ae904b5f6f" />

**Comment by Kvento** [comment]
I faced the same problem of color shift when extending the length of the video. After a couple of days I found what the problem was. It was due to incorrect color encoding in the video loader. If this is the problem, it is easy to track down, just take the first frame from the video and display it on the preview and compare it with the first frame from your video player. If this is the problem, you will immediately see a small color shift.
And yes, with multiple video extensions, the color shift also increases because it overlaps the previous color shift.

I solved the problem by using the "Load Video FFmpeg" node (VHS nodes) instead of the default "Load Video".

**Comment by pftq** [comment]
The examples I posted came from VACE's repo, without ComfyUI, so it's a different issue I think
https://github.com/ali-vilab/VACE/issues/44#issuecomment-2997681962

**Comment by bbaudio-2025** [comment]
This issue is not just color shift, but also includes a series of distortions such as blurred details, decreased contrast, and increased color saturation. I use a little trick in [my node](https://github.com/bbaudio-2025/ComfyUI-SuperUltimateVaceTools) to alleviate this distortion. It's not perfect and causes some color changes in the reference frames from previous video, but at least it can maintain the quality of the subsequent generated video to a certain extent and prevent it from deteriorating rapidly.

**Comment by jiangzeyinzi** [comment]
Could the user provide some cases (collecting ~10) that include src_video, src_mask, (ref_imgs), and caption, covering different color shift scenarios, to be used as a validation set?

**Comment by jaimitoes** [comment]
Resuming, it seems more evident in 4-8 steps configurations with Loras like light, face detailing, movie, etc. When you create your first video, the first generation change a bit the color palette and give details for humans... The problem of taking the last frame of a video to extend is that, you are recoloring an already recolored video, with all the consecuences, passing the detailer again, breaking the consistency of human faces...etc. A woman with few eyelashes appears with very long eyelashes extending the video 4 or 5 times and plastic skin. So the video is more burned on each generation (probally cause this distil, realism, detailer etc...Loras merged into).

**Comment by pftq** [comment]
I've been using the Wan 2.2 T2V low model substituted in for Wan 2.1 T2V, and as long as resolution is kept above 720p, the color drift issue is significantly reduced for inpainting (where most of the frame exists but has some details/objects masked out to autofill); painting entire frames is a bit less controlled but I generally get something good after a few takes at 50 steps.  The issue is still there but easier to patch in post-vfx with just 1-2 notches to Hue change and a slight gamma change in exposure.

Here's the workflow if it helps anyone else.
https://civitai.com/models/1536883

**Comment by rocky533** [comment]
This is a vace issue, but not just vace, its wan, it happens with image to video, text to video or anything you try to extend too far.  Its not just color, its contrast and quality that degrade the further you go.

Steps to REDUCE the drift (inside comfy) This will not solve it, as you can still only get a max of 6 batches before trouble and 8 before you cant use it.

Use FFMpeg loader, not load video from video helper suite.  Load video uses a different load than ffmpeg and it shifts more.
Use FP32 VAE not 16
Save high quality batches with as little compression as you can but watch the file sizes.. they get big.
Use larger batch sizes, vace can do 49-157 without issues usually.
Limit FPS to 1/2 of base and frame interpolate after.  This requires less batches so less drift for longer. 

Nodes that can help
Color Match nodes, (kjnodes, or many others) this can help when the drift is severe.  You can color match to your ref image if you did not remove background, or you can color match the last frame of the first clip, or you can color match the last frame of the previous video.  Many different color match types to try as well.  MKL usually being best at about 50%
Gamma correction node - (layerstyle nodes) can help on some videos when they contrast too much.  Some videos do this more than others.
Brightness and contrast node (layerstyle nodes) can help fix saturation levels or brightness and contrast.  

None of this fixes it.  It just reduces it.  Wan 2.2 does this much less but its still there but vace is not out for it and the fun models ... suck.

**Comment by pftq** [comment]
It's not a WAN issue - as mentioned before, a workaround is to use i2v wan
whenever possible because those come out with no color drifts compared to
the same run with wan vace.

**Comment by rocky533** [comment]
I have the issue with image to video as well.  It happens with any wan workflow i have used including wan animate, vace, i2v, t2v.  If it does not for you, im happy for you because it sucks.  Image to video is better but it hits a limit at about 8 batches for me unless I have start frames for each batch prepared as the moment i grab the last frame the drift begins.  

I also run a 3060 and can only do 848x480 generations, that may cause my issues to show more than people able to do 720p as from what i can tell larger drifts less.  

If there is anything that i have not stated that im missing let me know as i would also love to use something that does not drift.  And it may be something i am doing wrong with it. 

I can do any wan for about 6 batches at 30fps giving 486-750 frames with the drift being slight.  7-10 go a bit crazy.  more i just wont even try lol.  

Are you all doing 1 min videos via batching?  I havent seen this.  My max has been 53 seconds and it fell apart at the end.

**Comment by able2608** [comment]
Seems that newer models like stable video infinity and wan stable dancer fairs a bit better on this issue, being able to generate more than a minute of clip without any drifting (stable video infinity seems to even be able to do like 15 minutes at a time, and I have tested wan stable dancer and it is indeed able to do clips as long as a minute).
Stable video infinity seems to be a lora of some sort, not pretty sure if that is compatible to VACE. If it is compatible, then it might be the thing we all have been looking for.
